project:
  type: website

website:
  comments: 
    utterances:
      repo: soekni/Special-Rcology
  title: "Special-Rcology"
  favicon: images/favicon.ico
  page-navigation: true
  site-url: https://soekni.quarto.pub/special-rcology/
  reader-mode: true
  repo-url: https://github.com/soekni/Special-Rcology
  repo-actions: [edit, source, issue]
  page-footer:
    center:
      - href: index.qmd
        text: Home
  sidebar:
    title: Special-Rcology
    style: "docked"
    search: true
    collapse-level: 1
    logo: images/icon.png
    contents:
      - href: index.qmd
        text: Special-Rcology
      - href: about.qmd
        text: The Idea
      - href: authoring.qmd
        text: Authoring Content
      - href: Roadmap.qmd
        text: Roadmap
      - section: R,R,R
        contents:
        - href: R/Rste_Schritte.qmd
          text: Rste Schritte
        - href: R/approximation.qmd
          text: Approximation methods in the Bayesian universe

format:
  html:
    theme:
      light: [morph, custom_light.scss]
      dark: [darkly, custom_dark.scss]
    toc: true



