project:
  type: website
  output-dir: docs

website:
  title: "Special-Rcology"
  navbar:
    left:
      - href: about.qmd
        text: The Idea
      - href: authoring.qmd
        text: Authoring

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



