project:
  type: website
  output-dir: docs

website:
  title: "Special-Rcology"
  navbar:
    left:
      - href: about.qmd
        text: The Idea
      - href: authoring.qmd
        text: Authoring
      - href: R/Rste_Schritte.qmd
        text: Rste Schritte
      - href: Roadmap.qmd
        text: Roadmap

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



