---
title: "Special-Rcology"
---

🛠️ **This is a Quarto website still in development.** 🏗️

# Setup

You can easily contribute via github by following these steps:

-   "**Low key contribution**": Just leave a comment on the article you want to enhance. This is especially wanted for general feedback (structure, content etc.)!

-   "**I want to add notes myself!**"

No problem! It's very easy, really. To get started, watch this [video](https://youtu.be/CML6vfKjQss&t=1m45s) for 2 minutes and you're good to go!

Here's a transcript of what to do:

:::{.callout-important}
1.  Create a github account [here](https://github.com/login)!
2.  Install *git* on your machine.
3.  Go to the project's website [repository](https://github.com/soekni/Special-Rcology).
4.  Fork it by clicking the button on the top right!
5.  After linking the forked repo to your account, clone/download the files at your desired destination using:

``` r        
git clone https://github.com/soekni/Special-Rcology.git
```

in your terminal/console. <br>
Make sure to open the terminal at your desired location or change the directory using the "cd *locationToYourPath*".

:::

Now you're good to go! Change/Add files/notes using Quarto. Check out [this article](https://www.markdownguide.org/basic-syntax/) for learning the basics of markdown to just get started! <br>
If you want to learn more about authoring content/styling, visit the respective site in the navigation bar on the left.

# Further reading

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

# Troubleshooting

You can leave a comment or contact me directly when you're having issues following the setup. Ideally, this should be a "many hands make light work" - kind of thing.

<script src="https://utteranc.es/client.js"
        repo="soekni/Special-Rcology"
        issue-term="pathname"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>


